### PR TITLE
Fix wordconfidence and timestamps type

### LINKED ISSUE #12: [speech-to-text] SpeechRecognitionResult.WordConfidence Unmarshal Error
### Dependencies 
- Gorilla Websockets
- encoding/json

### Steps
- Connect to STT with Gorillas websocket connection, **RecognizeOptions.WordConfidence** = true, **model** = ja-JP_NarrowbandModel
- Wait for message via websocketConnection.ReadMessage()
- Unmarshal message to _speechtotextv1.SpeechRecognitionResults_

### Expected Behaviour
- Everything unmarshals nicely and no error

### Actual Behaviour
- **Error**: json: cannot unmarshal array into Go struct field _SpeechRecognitionAlternative.word_confidence_ of type string
- If **RecognizeOptions.WordConfidence** set to false, everything unmarshals correctly

### Go SDK version
v0.2.0

### Possible Cause
Watson returns _SpeechRecognitionAlternative.word_confidence_ as an array of ["string", int].

Should _SpeechRecognitionAlternative.word_confidence_ type be changed to accommodate this?

### PR DESCRIPTION
**Pull request by theThinkingCap**
### Summary

Fixes #12 and allows RecognizeResults to unmarshal correctly

### CODE REVIEW

**Comment by germanattanasio** [comment]
@theThinkingCap this looks good on paper, but the tests are failing because this repository isn't configured correctly to handle pull requests.

@ehdsouza, please add an `IF` statement in Travis to avoid issues trying to decrypt the `.env` file.
Something like:
```
'[ "${TRAVIS_PULL_REQUEST}" = "false" ] && openssl aes-256-cbc -K $encrypted_56d12e7424aa_key -iv $encrypted_56d12e7424aa_iv in .env.enc -out .env -d || true'
```
Rather than
```
openssl aes-256-cbc -K $encrypted_56d12e7424aa_key -iv $encrypted_56d12e7424aa_iv -in .env.enc -out .env -d
```

We do this for in the other SDKs, see [this](https://github.com/watson-developer-cloud/node-sdk/blob/master/.travis.yml#L7). 
You should also update the tests to make sure that integration tests run only if credentials are present.

**Comment by germanattanasio** [comment]
@theThinkingCap did you test this locally? if it's working I'm ok with approving it so we could merge it

**Comment by ehdsouza** [comment]
@theThinkingCap could you merge https://github.com/watson-developer-cloud/go-sdk/pull/15 into your PR to see if the build passes?

**Comment by theThinkingCap** [comment]
@ehdsouza Hmm... It seems like the Travis build is still failing

**Comment by ehdsouza** [comment]
Sorry, I didnt have the previous `openssl` command removed. Could you merge https://github.com/watson-developer-cloud/go-sdk/pull/17 and try

**Comment by theThinkingCap** [comment]
Everything seems to be running fine now!

**Pull request merged**
